version: "3"
services:
  php:
    image: platocreative/php:7.3-alpine3.8
    restart: unless-stopped
    environment:
      UID: ${UID}
      GID: ${GID}
      SMTP_LOGIN: developers@mailgun.platopreview.co.nz
      SMTP_PASSWORD: yVH-UaP-M6J-Dd9
    networks:
    - backend
    volumes:
    - www-sync:/var/www/html
  webserver:
    image: platocreative/httpd:2.4
    restart: unless-stopped
    environment:
      DOCUMENT_ROOT: /var/www/html/public
      SERVER_NAME: sciwifi.test
      SERVER_ALIAS: www.sciwifi.test
      VIRTUAL_HOST: sciwifi.test,www.sciwifi.test,~^www.sciwifi.test\..+\.xip\.io$$
    depends_on:
    - php
    - database
    networks:
    - backend
    - default
    expose:
    - 80
    - 443
    volumes:
    - www-sync:/var/www/html
  database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: plato
      MYSQL_PASSWORD: staff
      MYSQL_DATABASE: homestead
    volumes:
    - database:/var/lib/mysql
    - ./.docker/mysql/seed:/docker-entrypoint-initdb.d:ro
    networks:
    - backend
    labels:
    - db.network.tunnel.hostname=www.sciwifi.test
  composer:
    image: platocreative/composer
    volumes:
    - www-sync:/vendor
    command: composer install --ignore-platform-reqs
  node:
    image: node:10-jessie
    working_dir: /
    volumes:
    - www-sync:/node_modules
    command: npm install
  sync:
    image: platocreative/mutagen-sync
    command: tail -f /dev/null
    restart: unless-stopped
    volumes:
    - www-sync:/var/www/html:nocopy
networks:
  default:
    external:
      name: nginx-proxy
  backend: null
volumes:
  database: null
  www-sync: null
